### ISSUE TITLE
[Closed]Please help me check, for System.Threading, why can't I use online files, but only local files?

### ISSUE THREAD

**Issue by anqisoft** [DjDeveloperr/deno_win32#4]
console.log('Begin:', new Date());

// ok
import { Sleep as sleep_ok } from "../api/System/Threading.ts";
try {
    sleep_ok(1000);
    console.log('sleep_ok', new Date());
} catch(e) {
    console.error(e);
}

import { Sleep as sleep_0_4_1} from "https://win32.deno.dev/0.4.1/System.Threading";
try {
    sleep_0_4_1(1000);
    console.log('sleep_0_4_1', new Date());
} catch(e) {
    console.error(e);
}

import { Sleep as sleep_0_4_0} from "https://win32.deno.dev/0.4.0/System.Threading";
try {
    sleep_0_4_0(1000);
    console.log('sleep_0_4_0', new Date());
} catch(e) {
    console.error(e);
}

import { Sleep as sleep_0_2_0} from "https://win32.deno.dev/0.2.0/System.Threading";
try {
    sleep_0_2_0(1000);
    console.log('sleep_0_2_0', new Date());
} catch(e) {
    console.error(e);
}

console.log('End:', new Date());

/*
Begin: 2024-01-05T23:55:59.831Z
sleep_ok 2024-01-05T23:56:00.836Z
TypeError: Cannot read properties of undefined (reading 'Sleep')
    at Sleep (https://win32.deno.dev/0.4.1/System.Threading:9883:26)
    at file:///P:/anqi/Desktop/tech/deno/projects/deno_win32-main/anqi/threading.ts:24:5
TypeError: Cannot read properties of undefined (reading 'Sleep')
    at Sleep (https://win32.deno.dev/0.4.0/System.Threading:9883:26)
    at file:///P:/anqi/Desktop/tech/deno/projects/deno_win32-main/anqi/threading.ts:32:5
TypeError: Cannot read properties of undefined (reading 'Sleep')
    at Sleep (https://win32.deno.dev/0.2.0/System.Threading:6940:26)
    at file:///P:/anqi/Desktop/tech/deno/projects/deno_win32-main/anqi/threading.ts:40:5
End: 2024-01-05T23:56:00.867Z
*/

**Comment by anqisoft** [comment]
console.log('Begin:', new Date());
import { Sleep as sleep } from "https://github.com/DjDeveloperr/deno_win32/raw/main/api/System/Threading.ts";
try {
    sleep(1000);
    console.log('sleep', new Date());
} catch(e) {
    console.error(e);
}
console.log('End:', new Date());

/*
Begin: 2024-01-06T00:36:40.832Z
sleep 2024-01-06T00:36:41.975Z
End: 2024-01-06T00:36:41.976Z
*/
